[versions]
bytebuddy = "1.17.6"

[libraries]
aspectj = { module = "org.aspectj:aspectjweaver", version = "1.9.24" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
h2 = { module = "com.h2database:h2", version = "2.3.232" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.13.4" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.13.4" }
spring-aop = { module = "org.springframework:spring-aop", version = "6.2.10" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.0.2" }
bytebuddy = { id = "net.bytebuddy.byte-buddy-gradle-plugin", version.ref = "bytebuddy" }
